apiVersion: v1
kind: ConfigMap
metadata:
  name: traccar
data:
  traccar.xml: |
    <?xml version='1.0' encoding='UTF-8'?>

    <!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

    <properties>

        <entry key='config.default'>./conf/default.xml</entry> 

        <!--

        This is the main configuration file. All your configuration parameters should be placed in this file.

        Default configuration parameters are located in the "default.xml" file. You should not modify it to avoid issues
        with upgrading to a new version. Parameters in the main config file override values in the default file. Do not
        remove "config.default" parameter from this file unless you know what you are doing.

        For list of available parameters see following page: https://www.traccar.org/configuration-file/

        -->



        <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
        <entry key='database.url'>jdbc:mysql://{mysql_host}:3306/traccar?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=latin1&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
        <entry key='database.user'>{username}</entry>
        <entry key='database.password'>{password}</entry>

    </properties>


  default.xml: "<?xml version='1.0' encoding='UTF-8'?>\n\n<!DOCTYPE properties SYSTEM
    'http://java.sun.com/dtd/properties.dtd'>\n\n<properties>\n\n    <!--\n\n    DO
    NOT MODIFY THIS FILE. Use traccar.xml instead.\n\n    -->\n\n    <entry key='web.enable'>true</entry>\n
    \   <entry key='web.port'>8082</entry>\n    <entry key='web.path'>./web</entry>\n
    \   <entry key='web.cacheControl'>max-age=3600,public</entry>\n\n    <entry key='geocoder.enable'>false</entry>\n
    \   <entry key='geocoder.type'>google</entry>\n\n    <entry key='logger.enable'>true</entry>\n
    \   <entry key='logger.level'>info</entry>\n    <entry key='logger.file'>./logs/tracker-server.log</entry>\n
    \   <entry key='logger.rotate'>true</entry>\n\n    <entry key='filter.enable'>true</entry>\n
    \   <entry key='filter.future'>86400</entry>\n\n    <entry key='event.enable'>true</entry>\n
    \   <entry key='event.ignoreDuplicateAlerts'>true</entry>\n    <entry key='processing.computedAttributes.enable'>true</entry>\n
    \   <entry key='processing.engineHours.enable'>true</entry>\n\n    <entry key='media.path'>./media</entry>\n\n
    \   <entry key='notificator.types'>web,mail</entry>\n\n    <entry key='server.statistics'>https://www.traccar.org/analytics/</entry>\n\n
    \   <entry key='commands.queueing'>true</entry>\n\n    <entry key='database.ignoreUnknown'>true</entry>\n
    \   <entry key='database.generateQueries'>true</entry>\n    <entry key='database.changelog'>./schema/changelog-master.xml</entry>\n
    \n    <entry key='database.loginUser'>\n        SELECT * FROM tc_users\n        WHERE
    email = :email OR login = :email\n    </entry>\n\n    <entry key='database.selectPositions'>\n
    \       SELECT * FROM tc_positions WHERE deviceId = :deviceId AND fixTime BETWEEN
    :from AND :to ORDER BY fixTime\n    </entry>\n\n    <entry key='database.selectLatestPositions'>\n
    \       SELECT tc_positions.* FROM tc_positions INNER JOIN tc_devices ON tc_positions.id
    = tc_devices.positionid;\n    </entry>\n\n    <entry key='database.updateLatestPosition'>\n
    \       UPDATE tc_devices SET positionId = :id WHERE id = :deviceId\n    </entry>\n\n
    \   <entry key='database.selectEvents'>\n        SELECT * FROM tc_events WHERE
    deviceId = :deviceId AND serverTime BETWEEN :from AND :to ORDER BY serverTime\n
    \   </entry>\n\n    <entry key='database.deletePositions'>\n        DELETE FROM
    tc_positions WHERE serverTime &lt; :serverTime AND id NOT IN (SELECT positionId
    FROM tc_devices WHERE positionId IS NOT NULL)\n    </entry>\n\n    <entry key='database.deleteEvents'>\n
    \       DELETE FROM tc_events WHERE serverTime &lt; :serverTime\n    </entry>\n\n
    \   <entry key='database.selectStatistics'>\n        SELECT * FROM tc_statistics
    WHERE captureTime BETWEEN :from AND :to ORDER BY captureTime\n    </entry>\n\n
    \   <entry key='gps103.port'>5001</entry>\n    <entry key='tk103.port'>5002</entry>\n
    \   <entry key='gl100.port'>5003</entry>\n    <entry key='gl200.port'>5004</entry>\n
    \   <entry key='t55.port'>5005</entry>\n    <entry key='xexun.port'>5006</entry>\n
    \   <entry key='xexun.extended'>false</entry>\n    <entry key='totem.port'>5007</entry>\n
    \   <entry key='enfora.port'>5008</entry>\n    <entry key='meiligao.port'>5009</entry>\n
    \   <entry key='trv.port'>5010</entry>\n    <entry key='suntech.port'>5011</entry>\n
    \   <entry key='progress.port'>5012</entry>\n    <entry key='h02.port'>5013</entry>\n
    \   <entry key='jt600.port'>5014</entry>\n    <entry key='huabao.port'>5015</entry>\n
    \   <entry key='v680.port'>5016</entry>\n    <entry key='pt502.port'>5017</entry>\n
    \   <entry key='tr20.port'>5018</entry>\n    <entry key='navis.port'>5019</entry>\n
    \   <entry key='meitrack.port'>5020</entry>\n    <entry key='skypatrol.port'>5021</entry>\n
    \   <entry key='gt02.port'>5022</entry>\n    <entry key='gt06.port'>5023</entry>\n
    \   <entry key='megastek.port'>5024</entry>\n    <entry key='navigil.port'>5025</entry>\n
    \   <entry key='gpsgate.port'>5026</entry>\n    <entry key='teltonika.port'>5027</entry>\n
    \   <entry key='mta6.port'>5028</entry>\n    <entry key='tzone.port'>5029</entry>\n
    \   <entry key='tlt2h.port'>5030</entry>\n    <entry key='taip.port'>5031</entry>\n
    \   <entry key='wondex.port'>5032</entry>\n    <entry key='cellocator.port'>5033</entry>\n
    \   <entry key='galileo.port'>5034</entry>\n    <entry key='ywt.port'>5035</entry>\n
    \   <entry key='tk102.port'>5036</entry>\n    <entry key='intellitrac.port'>5037</entry>\n
    \   <entry key='gpsmta.port'>5038</entry>\n    <entry key='wialon.port'>5039</entry>\n
    \   <entry key='carscop.port'>5040</entry>\n    <entry key='apel.port'>5041</entry>\n
    \   <entry key='manpower.port'>5042</entry>\n    <entry key='globalsat.port'>5043</entry>\n
    \   <entry key='atrack.port'>5044</entry>\n    <entry key='pt3000.port'>5045</entry>\n
    \   <entry key='ruptela.port'>5046</entry>\n    <entry key='topflytech.port'>5047</entry>\n
    \   <entry key='laipac.port'>5048</entry>\n    <entry key='aplicom.port'>5049</entry>\n
    \   <entry key='gotop.port'>5050</entry>\n    <entry key='sanav.port'>5051</entry>\n
    \   <entry key='gator.port'>5052</entry>\n    <entry key='noran.port'>5053</entry>\n
    \   <entry key='m2m.port'>5054</entry>\n    <entry key='osmand.port'>5055</entry>\n
    \   <entry key='easytrack.port'>5056</entry>\n    <entry key='gpsmarker.port'>5057</entry>\n
    \   <entry key='khd.port'>5058</entry>\n    <entry key='piligrim.port'>5059</entry>\n
    \   <entry key='stl060.port'>5060</entry>\n    <entry key='cartrack.port'>5061</entry>\n
    \   <entry key='minifinder.port'>5062</entry>\n    <entry key='haicom.port'>5063</entry>\n
    \   <entry key='eelink.port'>5064</entry>\n    <entry key='box.port'>5065</entry>\n
    \   <entry key='freedom.port'>5066</entry>\n    <entry key='telic.port'>5067</entry>\n
    \   <entry key='trackbox.port'>5068</entry>\n    <entry key='visiontek.port'>5069</entry>\n
    \   <entry key='orion.port'>5070</entry>\n    <entry key='riti.port'>5071</entry>\n
    \   <entry key='ulbotech.port'>5072</entry>\n    <entry key='tramigo.port'>5073</entry>\n
    \   <entry key='tr900.port'>5074</entry>\n    <entry key='ardi01.port'>5075</entry>\n
    \   <entry key='xt013.port'>5076</entry>\n    <entry key='autofon.port'>5077</entry>\n
    \   <entry key='gosafe.port'>5078</entry>\n    <entry key='tt8850.port'>5079</entry>\n
    \   <entry key='bce.port'>5080</entry>\n    <entry key='xirgo.port'>5081</entry>\n
    \   <entry key='calamp.port'>5082</entry>\n    <entry key='mtx.port'>5083</entry>\n
    \   <entry key='tytan.port'>5084</entry>\n    <entry key='avl301.port'>5085</entry>\n
    \   <entry key='castel.port'>5086</entry>\n    <entry key='mxt.port'>5087</entry>\n
    \   <entry key='cityeasy.port'>5088</entry>\n    <entry key='aquila.port'>5089</entry>\n
    \   <entry key='flextrack.port'>5090</entry>\n    <entry key='blackkite.port'>5091</entry>\n
    \   <entry key='adm.port'>5092</entry>\n    <entry key='watch.port'>5093</entry>\n
    \   <entry key='t800x.port'>5094</entry>\n    <entry key='upro.port'>5095</entry>\n
    \   <entry key='auro.port'>5096</entry>\n    <entry key='disha.port'>5097</entry>\n
    \   <entry key='thinkrace.port'>5098</entry>\n    <entry key='pathaway.port'>5099</entry>\n
    \   <entry key='arnavi.port'>5100</entry>\n    <entry key='nvs.port'>5101</entry>\n
    \   <entry key='kenji.port'>5102</entry>\n    <entry key='astra.port'>5103</entry>\n
    \   <entry key='homtecs.port'>5104</entry>\n    <entry key='fox.port'>5105</entry>\n
    \   <entry key='gnx.port'>5106</entry>\n    <entry key='arknav.port'>5107</entry>\n
    \   <entry key='supermate.port'>5108</entry>\n    <entry key='appello.port'>5109</entry>\n
    \   <entry key='idpl.port'>5110</entry>\n    <entry key='huasheng.port'>5111</entry>\n
    \   <entry key='l100.port'>5112</entry>\n    <entry key='granit.port'>5113</entry>\n
    \   <entry key='carcell.port'>5114</entry>\n    <entry key='obddongle.port'>5115</entry>\n
    \   <entry key='hunterpro.port'>5116</entry>\n    <entry key='raveon.port'>5117</entry>\n
    \   <entry key='cradlepoint.port'>5118</entry>\n    <entry key='arknavx8.port'>5119</entry>\n
    \   <entry key='autograde.port'>5120</entry>\n    <entry key='oigo.port'>5121</entry>\n
    \   <entry key='jpkorjar.port'>5122</entry>\n    <entry key='cguard.port'>5123</entry>\n
    \   <entry key='fifotrack.port'>5124</entry>\n    <entry key='smokey.port'>5125</entry>\n
    \   <entry key='extremtrac.port'>5126</entry>\n    <entry key='trakmate.port'>5127</entry>\n
    \   <entry key='at2000.port'>5128</entry>\n    <entry key='maestro.port'>5129</entry>\n
    \   <entry key='ais.port'>5130</entry>\n    <entry key='gt30.port'>5131</entry>\n
    \   <entry key='tmg.port'>5132</entry>\n    <entry key='pretrace.port'>5133</entry>\n
    \   <entry key='pricol.port'>5134</entry>\n    <entry key='siwi.port'>5135</entry>\n
    \   <entry key='starlink.port'>5136</entry>\n    <entry key='dmt.port'>5137</entry>\n
    \   <entry key='xt2400.port'>5138</entry>\n    <entry key='dmthttp.port'>5139</entry>\n
    \   <entry key='alematics.port'>5140</entry>\n    <entry key='gps056.port'>5141</entry>\n
    \   <entry key='flexcomm.port'>5142</entry>\n    <entry key='vt200.port'>5143</entry>\n
    \   <entry key='owntracks.port'>5144</entry>\n    <entry key='vtfms.port'>5145</entry>\n
    \   <entry key='tlv.port'>5146</entry>\n    <entry key='esky.port'>5147</entry>\n
    \   <entry key='genx.port'>5148</entry>\n    <entry key='flespi.port'>5149</entry>\n
    \   <entry key='dway.port'>5150</entry>\n    <entry key='recoda.port'>5151</entry>\n
    \   <entry key='oko.port'>5152</entry>\n    <entry key='ivt401.port'>5153</entry>\n
    \   <entry key='sigfox.port'>5154</entry>\n    <entry key='t57.port'>5155</entry>\n
    \   <entry key='spot.port'>5156</entry>\n    <entry key='m2c.port'>5157</entry>\n
    \   <entry key='austinnb.port'>5158</entry>\n    <entry key='opengts.port'>5159</entry>\n
    \   <entry key='cautela.port'>5160</entry>\n    <entry key='continental.port'>5161</entry>\n
    \   <entry key='egts.port'>5162</entry>\n    <entry key='robotrack.port'>5163</entry>\n
    \   <entry key='pt60.port'>5164</entry>\n    <entry key='telemax.port'>5165</entry>\n
    \   <entry key='sabertek.port'>5166</entry>\n    <entry key='retranslator.port'>5167</entry>\n
    \   <entry key='svias.port'>5168</entry>\n    <entry key='eseal.port'>5169</entry>\n
    \   <entry key='freematics.port'>5170</entry>\n    <entry key='avema.port'>5171</entry>\n
    \   <entry key='autotrack.port'>5172</entry>\n    <entry key='tek.port'>5173</entry>\n
    \   <entry key='wristband.port'>5174</entry>\n    <entry key='applet.port'>5175</entry>\n
    \   <entry key='milesmate.port'>5176</entry>\n    <entry key='anytrek.port'>5177</entry>\n
    \   <entry key='smartsole.port'>5178</entry>\n    <entry key='its.port'>5179</entry>\n
    \   <entry key='xrb28.port'>5180</entry>\n    <entry key='c2stek.port'>5181</entry>\n
    \   <entry key='nyitech.port'>5182</entry>\n    <entry key='neos.port'>5183</entry>\n
    \   <entry key='satsol.port'>5184</entry>\n    <entry key='globalstar.port'>5185</entry>\n
    \   <entry key='sanul.port'>5186</entry>\n    <entry key='minifinder2.port'>5187</entry>\n
    \   <entry key='radar.port'>5188</entry>\n    <entry key='techtlt.port'>5189</entry>\n
    \   <entry key='starcom.port'>5190</entry>\n    <entry key='mictrack.port'>5191</entry>\n
    \   <entry key='plugin.port'>5192</entry>\n    <entry key='leafspy.port'>5193</entry>\n
    \   <entry key='naviset.port'>5194</entry>\n\n</properties>\n"
