apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traccar
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`traccar.pik8s.home`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: traccar
      port: 8082
